### ISSUE TITLE
Microsoft Edge's Logo

### ISSUE THREAD

**Issue by CrownedComedian** [CrownedComedian/Hello_World#1]
This is the ugliest thing

![image](https://cloud.githubusercontent.com/assets/7825233/9266679/81576e50-4212-11e5-989b-5e3a70a3b6d7.png)

**Comment by patrickkettner** [comment]
Iuno. I've seen worse.

**Comment by CrownedComedian** [comment]
Microsoft has removed this logo from edge and replaced it with a still-not-that-good-looking-but-not-as-bad logo.
